name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y xxd

      - name: Build
        run: make

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            copy_fail_exp
            copy_fail_exp.py
